# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 80
#    context-path: /

# mysql
spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    # 指定静态资源的路径
#    resources:
#        static-locations: classpath:/static/,classpath:/views/,classpath:/
#redis配置
    redis:
#        open: true  # 是否开启redis缓存  true 开启   false 关闭
        # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
        database: 0
        # redis服务器地址（默认为localhost）
        host: 47.92.96.175
        # redis端口（默认为6379）
        port: 6379
        # redis访问密码（默认为空）
        password:       # 密码（默认为空）
        # redis连接超时时间（单位为毫秒）
        timeout: 6000  # 连接超时时长（毫秒）
        # redis连接池配置
        pool:
            # 最大可用连接数（默认为8，负数表示无限）
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            # 最大空闲连接数（默认为8，负数表示无限）
            max-idle: 10      # 连接池中的最大空闲连接
            # 最小空闲连接数（默认为0，该值只有为正数才有作用）
            min-idle: 5       # 连接池中的最小空闲连接
            # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis.xml